# Get editor completions based on the config schema
"$schema" = '~/.config/config-schema.json'

format = " [ $directory ](blue)[‚ùØ](bold green) "

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
format = "$path"
truncation_length = 100
